### ISSUE TITLE
update decimal places for psra  ect_fatality, ectr_fatality

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/model-factory#141]
After discussion with @plesueur. Update fatality indicators from original 6dp to 10dp to capture more values.

**Comment by plesueur** [comment]
one thing to note @wkhchow, this will change the normalized risk scores, and therefore the normalized risk ratings.. Did we implement the jenks algorithm to calculate the thresholds for the rating in your database? If not, I'll need to do this externally before we propagate the dataset through the publishing process.

**Comment by wkhchow** [comment]
changes applied in newest model_factory branch
https://github.com/OpenDRR/model-factory/commit/3d776328bab4e2c481ac7d4c4dd896a33e54e21e

**Comment by wkhchow** [comment]
> one thing to note @wkhchow, this will change the normalized risk scores, and therefore the normalized risk ratings.. Did we implement the jenks algorithm to calculate the thresholds for the rating in your database? If not, I'll need to do this externally before we propagate the dataset through the publishing process.

Jenks applied to the risk scores for sauid, csd and all hexgrid variations. Using ESRI ArcMap symbolization, and selecting entire data for sample to get correct jenks thresholds
