### ISSUE TITLE
DSRA: Replace SQL 'COPY' command to \copy and move from sql scrip to os.system call throughout stack workflow. Multiple instances.

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/model-factory#46]

**Comment by wkhchow** [comment]
New branch created to support test \ support changes
https://github.com/OpenDRR/model-factory/tree/add_psra_sql_copy_fix

- removed (commented out) all 'copy from' and subsequent queries from create table sql scripts.
- combined all the subsequent queries in the create table scripts into Create_all_tables_update.sql.  Should add/run in add_data.sh before creating the indicators.
- PSRA - combined all 3 create tables into 1 sql file psra_1.Create_tables.sql, commented out copy from / subsequent queries.  Combined all subsequent queries into psra_2.Create_table_updates.sql.
