### ISSUE TITLE
update \copy statements for new changes in update_sovi_hazthreat_feb2021 branch

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/model-factory#56]
Updates to be made in update_sovi_hazthreat_feb2021 branch
https://github.com/OpenDRR/model-factory/tree/update_sovi_hazthreat_feb2021/scripts

**copyAncillaryTables.py**
- UPDATE/ADD copy statements for:

- [x] Create_table_mh_intensity_canada_v2.sql

- [x] Create_table_mh_thresholds.sql
- [x] Create_table_sovi_census_canada.sql
- [x] Create_table_sovi_index_canada_v2.sql
- [x] Create_table_sovi_thresholds.sql
- [x] Create_psra_merge_into_national_indicators.sql
- [x] Create_scenario_risk_master_tables.sql

**PSRA_copyTables.py**
- ADD copy statement for:
- [x] psra_1.Create_tables.sql (xref create table line starts from 498 - 544, processing xref code commented out in psra_2)

**Comment by wkhchow** [comment]
@drotheram 
additional sql script added to combine PSRA levels to the national level.

https://github.com/OpenDRR/model-factory/blob/update_sovi_hazthreat_feb2021/scripts/psra_6.Create_psra_merge_into_national_indicators.sql

Can be injected into add_data.sh after all PSRA is run (after line 514?)

**Comment by wkhchow** [comment]
@drotheram 
additional sql script added to combine DSRA to create master scenario tables.
https://github.com/OpenDRR/model-factory/blob/update_sovi_hazthreat_feb2021/scripts/Create_scenario_risk_master_tables.sql

Can be injected into add_data.sh after DSRA is run (514).

**Comment by wkhchow** [comment]
Merge boundaries repo PR into master before testing this rebuild.
https://github.com/OpenDRR/boundaries/pull/11

**Comment by jvanulde** [comment]
@drotheram @wkhchow is this done?

**Comment by drotheram** [comment]
Yes, we can close this issue
