### ISSUE TITLE
DSRA - "gmpe_Model" indicator defaults to  value "NBCC2020_TEST_PLACEHOLDER" for all views

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/model-factory#57]
Just noticed all our DSRA views for "gmpe_Model" indicator defaults to "NBCC2020_TEST_PLACEHOLDER" and comes set a default value from DSRA_outputs2postgres_lfs.py

https://github.com/OpenDRR/model-factory/blob/master/scripts/DSRA_outputs2postgres_lfs.py

Need to check and verify actual source of gmpe values.

**Comment by drotheram** [comment]
This is a hardcoded placeholder, we should discuss where we need to parse this from.

**Comment by jvanulde** [comment]
> This is a hardcoded placeholder, we should discuss where we need to parse this from.

Can you provide the permalink to the offending line please...

**Comment by drotheram** [comment]
https://github.com/OpenDRR/model-factory/blob/c2e08f87b913741363a8cb0645927bc2562d3f19/scripts/DSRA_outputs2postgres_lfs.py#L153

**Comment by tieganh** [comment]
So the correct place to get this value would be in the appropriate s_Hazard_NAME_ATTRIB.ini file, under the `gsim_logic_tree_file` attribute. For example: 

https://github.com/OpenDRR/earthquake-scenarios/blob/master/initializations/s_Hazard_SIM9p0_CascadiaInterfaceBestFault.ini#L15

**Comment by wkhchow** [comment]
Tiegan mentioned the xml name can also be extracted from the scenario.md file under gsim_logic_tree_file.

**Comment by drotheram** [comment]
Fixed by @DamonU2. Issue will be closed when 'update_hexbin_and_dsra_source' branch is merged to main branch

**Comment by wkhchow** [comment]
@DamonU2 has fixed the issue.
