### ISSUE TITLE
DSRA updates for new scenarios (b0/r1)

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/model-factory#59]
Tiegan's new revised scenarios are now running off b0/r1 instead of the previous iterations of b0/r2.  
Must make changes to @drotheram 's DSRA to postgres python scripts and my dsra indicator scripts as they will no longer work.
Need to confirm whether to have the previous b0/r2 scenarios run as well or those will be recalculated to run off b0/r1.

**Comment by wkhchow** [comment]
After our meeting with Tiegan.  Current concensus to get the scenarios running off the bat without significant changes is to rename source  the new scenario b0/r1 to b0/r2.  Edit indicator names in postgis from b0/r2 to b0/r1 to reflect this change.  

Will revisit and correct codes to reflect b0/r1 at a later time.

**Comment by jvanulde** [comment]
@wkhchow can we close?

**Comment by wkhchow** [comment]
Yes.  Will revisit for next iteration.
