### ISSUE TITLE
Eliminate the use of 'all_indicators' 

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/model-factory#80]
The use of 'all_indicators' has become redundant now that we have eliminated the thematic indicators. 

Let's change the use of 'all_indicators' in postgis to simply 'indicators' and propagate those changes to the ES indices as well

**Comment by wkhchow** [comment]
I will start implementing on my end in once we finish current PR and have it in the new branch along with psra/dsra updates that are coming.

**Comment by drotheram** [comment]
Should be fixed in merge of update_dsra_psra_oct2021
